---
# tasks file for ansible_role_with_molecule_github_actions
- name: example install package
  package:
    name: httpd
    state: present

- name: Start service httpd, if not started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
    with_items:
      - httpd
